export const COLOR_SATURATION_THRESHOLD = 0.05;
export const COLOR_PAGE_COVERAGE_THRESHOLD = 0.05;
export const FULL_COLOR_PAGE_COVERAGE_THRESHOLD = 0.95;
export const MIN_CONTENT_COVERAGE_THRESHOLD = 0.001;
export const LOW_CONTENT_COVERAGE_THRESHOLD = 0.02;
export const PDF_RENDER_SCALE = 0.35;
export const MAX_PIXELS_TO_SAMPLE = 200_000;
